export { useSetting } from "./useSetting";
export { useRole} from "./useRole";
export { useTeacher } from "./useTeacher";
export { useClassroom } from "./useClassroom";
export { useStudent } from "./useStudent";
export { usePaymentType } from "./usePaymentType";
export { useSchoolYear } from "./useSchoolYear";
export { useBill } from "./useBill";
export { useUser } from "./useUser";
export { useMajor } from "./useMajor";
